services:
  webui:
    build:
      context: .
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ports:
      - "7860:7861"
    tty: true
    volumes:
      - "./project:/home/app/project:rw"
