services:
  webui:
    image: registry-1.deepsquare.run/library/automatic111:gpu
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - COMMANDLINE_ARGS=--allow-code --medvram --xformers --enable-insecure-extension-access --api
    ports:
      - "7860:7860"
    tty: true
    volumes:
      - "./project:/home/app/project:rw"
